# Generated by Django 3.1.7 on 2021-05-14 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=30)),
                ('ability_description', models.CharField(blank=True, max_length=250, null=True)),
                ('ability_level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('ability_is_magical', models.BooleanField(default=False)),
                ('ability_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('hit_points', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('magic_points', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('damage_points', models.IntegerField(blank=True, null=True)),
                ('special_ability', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_name', models.CharField(choices=[('HUMAN', 'Human'), ('DWARF', 'Dwarf'), ('ELF', 'Elf'), ('HALF_ELF', 'Half-Elf'), ('HALFLING', 'Halfling'), ('TIEFLING', 'Tiefling')], max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('special_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Player_character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.information')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.player_character')),
            ],
        ),
        migrations.CreateModel(
            name='Job_class',
            fields=[
                ('class_id', models.CharField(choices=[('HUNTER', 'Hunter'), ('ASSASSIN', 'Assassing'), ('THIEF', 'Thief'), ('PALADIN', 'Paladin'), ('DRUID', 'Druid'), ('WIZARD', 'Wizard'), ('NONE', 'None')], max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('special_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='char_sheet.abilities')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.items')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='job_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.job_class'),
        ),
        migrations.AddField(
            model_name='information',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.race'),
        ),
        migrations.CreateModel(
            name='Character_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.information')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.items')),
            ],
        ),
        migrations.CreateModel(
            name='Character_abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_points', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('abilities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.abilities')),
                ('information_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.information')),
            ],
        ),
    ]
