# Generated by Django 3.1.7 on 2021-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_class',
            name='class_id',
            field=models.CharField(choices=[('HUNTER', 'Hunter'), ('ASSASSIN', 'Assassin'), ('THIEF', 'Thief'), ('PALADIN', 'Paladin'), ('DRUID', 'Druid'), ('WIZARD', 'Wizard'), ('NONE', 'None')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
