# Generated by Django 3.1.7 on 2021-05-15 08:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0002_auto_20210514_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enchantements',
            fields=[
                ('enchantement_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_damage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(-30)])),
            ],
        ),
        migrations.CreateModel(
            name='Item_enchantements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enchantement_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.enchantements')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.items')),
            ],
        ),
        migrations.RemoveField(
            model_name='player_character',
            name='information_id',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Player_character',
        ),
    ]
