# Generated by Django 3.1.7 on 2021-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0004_player_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
